#!/usr/bin/env python3
"""Levels/Level_N.as (JPEXS export) -> src/level_polys.h

Emits, for every Level.CreateBody(...) call of the listed levels, the polygon list verbatim (the AS3 numeric
literals are copied as text, so the C++ compiler parses exactly the same doubles) as
    static const PolyList kL<level>_<name> = {...};
Calls whose name is an expression ("vagon" + i) get a suffix by order of appearance in the file
(kL11_vagon_1, kL11_vagon_2). Circle bodies are not emitted (the size is a literal in the script).
Usage: gen_level_polys.py <scripts/Levels dir> > src/level_polys.h
"""
import re, sys
LEVELS = (9, 10, 11, 13, 15, 16, 17)
src_dir = sys.argv[1]

def scan_call(s, i):
    """s[i] == '(' -> index of the matching ')'; skips string literals."""
    depth = 0
    k = i
    while True:
        c = s[k]
        if c == '"':
            k = s.index('"', k + 1)
        elif c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
            if depth == 0:
                return k
        k += 1

def split_args(a):
    out, depth, cur, k = [], 0, '', 0
    while k < len(a):
        c = a[k]
        if c == '"':
            e = a.index('"', k + 1)
            cur += a[k:e + 1]; k = e + 1; continue
        if c in '([': depth += 1
        if c in ')]': depth -= 1
        if c == ',' and depth == 0:
            out.append(cur.strip()); cur = ''
        else:
            cur += c
        k += 1
    out.append(cur.strip())
    return out

def to_cpp(arr):
    # [[[x,y],...],...] -> {{{x, y}, ...}, ...}
    return arr.replace('[', '{').replace(']', '}').replace(',', ', ')

out = ["// Generated by tools/gen_level_polys.py from the SWF's Levels/Level_N.as -- do not edit.",
       "// Polygon lists of Level.CreateBody calls, in pixels, exactly as written in the AS3 source.",
       "#pragma once", "#include \"redball.h\"", "namespace rb {"]
for L in LEVELS:
    s = open(f"{src_dir}/Level_{L}.as", encoding="utf-8").read().replace("\r", "")
    expr_count = {}
    for m in re.finditer(r'\bCreateBody\(', s):
        i = m.end() - 1
        j = scan_call(s, i)
        args = split_args(s[i + 1:j])
        if len(args) < 6 or args[1] != '"Polygon"' and args[1] != '"BluePolygon"':
            continue
        name = args[0]
        if name.startswith('"') and name.endswith('"') and '+' not in name:
            ident = name.strip('"')
        else:
            base = re.match(r'"([A-Za-z0-9_]+)"', name).group(1)
            expr_count[base] = expr_count.get(base, 0) + 1
            ident = f"{base}_{expr_count[base]}"
        line = f"static const PolyList kL{L}_{ident} = {to_cpp(args[5])};"
        if line in out:
            continue  # a re-creation of the same body with the same polygons (Update)
        if any(o.startswith(f"static const PolyList kL{L}_{ident} =") for o in out):
            sys.exit(f"{L}_{ident}: same name, different polygons")
        out.append(line)
out.append("}  // namespace rb")
print("\n".join(out))
