#!/usr/bin/env python3
"""Emit src/flash_sintab.h (Flash's display-matrix sine table, fitted in docs/STATS_LOGGING.md 3.7)."""
import math
vals=[math.trunc(math.sin(i*0.25*(math.pi/180))*(1<<30)) for i in range(362)]
print("// Generated by tools/gen_flash_sintab.py -- do not edit.")
print("// Flash Player 11.4 display-matrix sine table: trunc(sin(i * 0.25 deg) * 2^30), i = 0..361.")
print("// Fitted to 14,500 logged matrices (docs/STATS_LOGGING.md 3.7).")
print("#pragma once\n#include <cstdint>\nnamespace rb {\nstatic const int64_t kFlashSinTab[362] = {")
for i in range(0,362,6): print("    "+", ".join(str(v) for v in vals[i:i+6])+",")
print("};\n}  // namespace rb")
