#!/usr/bin/env python3
"""levels.json (tools/extract_levels.py) -> src/levels_data.h"""
import json, sys
L = json.load(open(sys.argv[1]))
out = ["// Generated by tools/gen_levels_data.py from the SWF's Levels.Level_N sprites.",
       "// Named first-frame placements: translate in twips, matrix a,b,c,d in 16.16 fixed point.",
       "#pragma once", "#include <cstdint>", "namespace rb {",
       "struct RawPlacement { const char* name; int32_t tx, ty, a, b, c, d; };",
       "struct LevelPlacements { int32_t id; const RawPlacement* items; int32_t count; };"]
ids = sorted(int(k) for k in L)
for i in ids:
    items = sorted(L[str(i)].items(), key=lambda kv: kv[1]['depth'])
    out.append(f"static const RawPlacement kLevel{i}Placements[] = {{")
    for n, p in items:
        out.append(f'    {{"{n}", {p["tx"]}, {p["ty"]}, {p["a"]}, {p["b"]}, {p["c"]}, {p["d"]}}},')
    out.append("};")
out.append("static const LevelPlacements kLevelPlacements[] = {")
for i in ids:
    out.append(f"    {{{i}, kLevel{i}Placements, (int32_t)(sizeof(kLevel{i}Placements) / sizeof(RawPlacement))}},")
out.append("};")
out.append("}  // namespace rb")
print("\n".join(out))
