#!/usr/bin/env python3
"""Generate src/display_data.h: first-frame local bounds (twips) of every named
object of every Level_N sprite, as Flash's getBounds() sees them (shapeBounds,
morph shapes at their placement ratio, nested sprites unioned).  Used by the
display layer (hitTestObject for goal/checkpoints).  usage:
  gen_display_data.py practice_full.xml > src/display_data.h"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
import swf_geom as g
g.load(sys.argv[1])
LEVELS={1:401,2:355,3:575,4:561,5:125,6:434,7:287,8:389,9:248,10:205,11:87,12:164,13:601,14:536,15:474,16:328,17:493}
print("// Generated by tools/gen_display_data.py -- do not edit.")
print("// Level-local AABB (twips) of each named first-frame object, placement matrix applied.")
print("// exact=1: identity/translate-only placement (bounds are integers); 0: rotated/scaled (needs calibration).")
print("#pragma once\n#include <cstdint>\nnamespace rb {\nstruct DisplayObj { const char* name; double x0, y0, x1, y1; int32_t exact; };")
print("struct LevelDisplay { int32_t id; const DisplayObj* items; int32_t count; };")
for lid,sid in LEVELS.items():
    print("static const DisplayObj kLevel%dDisplay[] = {"%lid)
    for n,v in g.level(sid).items():
        if n.startswith('depth') or v['b'] is None: continue
        r=g.xrect(v['b'],v['m']); a,b,c,d,_,_=v['m']
        ex=int(abs(a-1)<1e-12 and abs(d-1)<1e-12 and b==0 and c==0)
        print('    {"%s", %r, %r, %r, %r, %d},'%(n,*[float(x) for x in r],ex))
    print("};")
print("static const LevelDisplay kDisplayTable[] = {")
for lid in LEVELS: print("    {%d, kLevel%dDisplay, (int32_t)(sizeof(kLevel%dDisplay) / sizeof(DisplayObj))},"%(lid,lid,lid))
print("};\n}  // namespace rb")
