#!/usr/bin/env python3
"""Generate src/display_data.h: first-frame local bounds (twips) of every named
object of every Level_N sprite, as Flash's getBounds() sees them (shapeBounds,
morph shapes at their placement ratio, nested sprites unioned).  Used by the
display layer (hitTestObject for goal/checkpoints).  usage:
  gen_display_data.py practice_full.xml > src/display_data.h"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
import swf_geom as g
g.load(sys.argv[1])
LEVELS={1:401,2:355,3:575,4:561,5:125,6:434,7:287,8:389,9:248,10:205,11:87,12:164,13:601,14:536,15:474,16:328,17:493}
print("// Generated by tools/gen_display_data.py -- do not edit.")
print("// Level-local AABB (twips) of each named first-frame object, placement matrix applied.")
print("// exact=1: identity/translate-only placement (bounds are integers); 0: rotated/scaled (needs calibration).")
print("#pragma once\n#include <cstdint>\nnamespace rb {\nstruct DisplayObj { const char* name; double x0, y0, x1, y1; int32_t exact; };")
print("struct LevelDisplay { int32_t id; const DisplayObj* items; int32_t count; };")
for lid,sid in LEVELS.items():
    print("static const DisplayObj kLevel%dDisplay[] = {"%lid)
    for n,v in g.level(sid).items():
        if n.startswith('depth') or v['b'] is None: continue
        r=g.xrect(v['b'],v['m']); a,b,c,d,_,_=v['m']
        ex=int(abs(a-1)<1e-12 and abs(d-1)<1e-12 and b==0 and c==0)
        print('    {"%s", %r, %r, %r, %r, %d},'%(n,*[float(x) for x in r],ex))
    print("};")
# Spikes: every top-level Ships10 (58) / Shipik (57) placement of a level (Level.Update walks its own
# children). Per Shipik: its transform into Level space (px) and its getBounds(Level) rectangle (twips).
# Shipik.testPoint (MATHSPIKES = 1) uses the triangle (0,0) (w/2,-h) (w,0), w = 6, h = 9.65 px.
SHIPIK, SHIPS10 = 57, 58
SHAPE = (0, -193, 120, 0)  # shape 56 bounds, twips
def mul(m, n):  # m after n
    a,b,c,d,tx,ty = m; a2,b2,c2,d2,tx2,ty2 = n
    return (a*a2 + c*b2, b*a2 + d*b2, a*c2 + c*d2, b*c2 + d*d2, a*tx2 + c*ty2 + tx, b*tx2 + d*ty2 + ty)
def spikes(sid):
    out = []
    kind, sp = g.chars[sid]
    for k in g.frame1_children(sp):
        cid = int(k.get('characterId') or -1)
        if cid not in (SHIPIK, SHIPS10): continue
        m = g.mat(k)
        subs = [g.mat(c) for c in g.frame1_children(g.chars[SHIPS10][1])] if cid == SHIPS10 else [(1, 0, 0, 1, 0, 0)]
        for sm in subs:
            M = mul(m, sm)
            if cid == SHIPS10:  # nested box-in-a-box: Shipik box in Ships10 space, rounded, then Ships10's transform
                inner = g.xrect(SHAPE, sm); inner = tuple(float(round(v)) for v in inner)
                bx = g.xrect(inner, m)
            else:
                bx = g.xrect(SHAPE, M)
            bx = tuple(float(round(v)) for v in bx)
            out.append((k.get('name') or '', M, bx))
    return out
print("// Shipik in Level space: L = (a*x + c*y + tx, b*x + d*y + ty) px; bounds = getBounds(Level), twips.")
print("struct SpikeObj { double a, b, c, d, tx, ty; double bx0, by0, bx1, by1; };")
print("struct LevelSpikes { int32_t id; const SpikeObj* items; int32_t count; };")
spk = {}
for lid, sid in LEVELS.items():
    spk[lid] = spikes(sid)
    if not spk[lid]: continue
    print("static const SpikeObj kLevel%dSpikes[] = {" % lid)
    for name, M, bx in spk[lid]:
        a,b,c,d,tx,ty = M
        print("    {%r, %r, %r, %r, %r, %r, %r, %r, %r, %r},  // %s" % (float(a), float(b), float(c), float(d), tx/20.0, ty/20.0, *bx, name))
    print("};")
print("static const LevelSpikes kSpikeTable[] = {")
for lid in LEVELS:
    if spk[lid]: print("    {%d, kLevel%dSpikes, (int32_t)(sizeof(kLevel%dSpikes) / sizeof(SpikeObj))}," % (lid, lid, lid))
print("};")
print("static const LevelDisplay kDisplayTable[] = {")
for lid in LEVELS: print("    {%d, kLevel%dDisplay, (int32_t)(sizeof(kLevel%dDisplay) / sizeof(DisplayObj))},"%(lid,lid,lid))
print("};\n}  // namespace rb")
